url: https://paperswelove.ro
baseurl: ''
enforce_ssl: paperswelove.ro
safe: true
lsi: false
sass:
    style: compressed

compass:
  logo: "/favicon.ico"
  author: "Papers We Love Romania"
  tagline: "Community built around reading, discussing and learning more about academic computer science papers."
  include_content: true
  include_analytics: false

markdown: kramdown
highlighter: rouge

permalink: pretty

# Settings for deploy rake task
username:        papers-we-love-ro
repo:            paperswelove.ro
branch:          source
relative_source: ../paperswelove.ro/
destination:     ../paperswelove.ro-pages/
production_url:  https://paperswelove.ro
source_url:      https://github.com/papers-we-love-ro/paperswelove.ro
