url: https://paperswelove.ro
baseurl: ''

compass:
  logo: "/images/logo.png"
  author: "Papers We Love Romania"
  tagline: "Community built around reading, discussing and learning more about academic computer science papers."
  include_content: true
  include_analytics: false

markdown: kramdown
highlighter: rouge

permalink: pretty
